// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(TurnoMolarDbContext))]
    partial class TurnoMolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.AtencionOdontologica", b =>
                {
                    b.Property<int>("CodAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAtencion"));

                    b.Property<int>("CodTurno")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("FechaYHoraAtencionFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaYHoraAtencionInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaYHoraReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("NroHC")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PacienteNroDoc")
                        .HasColumnType("int");

                    b.Property<string>("PacienteTipoDoc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CodAtencion");

                    b.HasIndex("CodTurno")
                        .IsUnique();

                    b.HasIndex("NroHC");

                    b.ToTable("AtencionesMedicas", (string)null);

                    b.HasDiscriminator().HasValue("AtencionOdontologica");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Model.ComprobanteDeTurno", b =>
                {
                    b.Property<int>("NroComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroComprobante"));

                    b.Property<int>("CodTurno")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaYHoraEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaYHoraReserva")
                        .HasColumnType("datetime2");

                    b.HasKey("NroComprobante");

                    b.HasIndex("CodTurno")
                        .IsUnique();

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("Domain.Model.DetalleInsumoUtilizado", b =>
                {
                    b.Property<int>("CodInsumo")
                        .HasColumnType("int");

                    b.Property<int>("CodAtencion")
                        .HasColumnType("int");

                    b.Property<int>("CantidadUtilizada")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitarioAlMomento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodInsumo", "CodAtencion");

                    b.HasIndex("CodAtencion");

                    b.ToTable("DetallesInsumos");
                });

            modelBuilder.Entity("Domain.Model.DisponibilidadHoraria", b =>
                {
                    b.Property<int>("CodDisponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodDisponibilidad"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("CodDisponibilidad");

                    b.ToTable("DisponibilidadesHorarias");

                    b.HasData(
                        new
                        {
                            CodDisponibilidad = 1,
                            DiaSemana = "Lunes",
                            HoraFin = new TimeOnly(16, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            CodDisponibilidad = 2,
                            DiaSemana = "Martes",
                            HoraFin = new TimeOnly(17, 0, 0),
                            HoraInicio = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            CodDisponibilidad = 3,
                            DiaSemana = "Miércoles",
                            HoraFin = new TimeOnly(18, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            CodDisponibilidad = 4,
                            DiaSemana = "Jueves",
                            HoraFin = new TimeOnly(14, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            CodDisponibilidad = 5,
                            DiaSemana = "Viernes",
                            HoraFin = new TimeOnly(13, 0, 0),
                            HoraInicio = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("Domain.Model.Especialidad", b =>
                {
                    b.Property<int>("CodEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodEspecialidad"));

                    b.Property<decimal>("ArancelParticular")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodEspecialidad");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            CodEspecialidad = 1,
                            ArancelParticular = 15000m,
                            Nombre = "Odontología General"
                        },
                        new
                        {
                            CodEspecialidad = 2,
                            ArancelParticular = 35000m,
                            Nombre = "Endodoncia"
                        },
                        new
                        {
                            CodEspecialidad = 3,
                            ArancelParticular = 50000m,
                            Nombre = "Ortodoncia"
                        },
                        new
                        {
                            CodEspecialidad = 4,
                            ArancelParticular = 80000m,
                            Nombre = "Cirugía e Implantes"
                        },
                        new
                        {
                            CodEspecialidad = 5,
                            ArancelParticular = 12000m,
                            Nombre = "Odontopediatría"
                        });
                });

            modelBuilder.Entity("Domain.Model.HistoriaClinica", b =>
                {
                    b.Property<int>("NroHC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroHC"));

                    b.Property<string>("Alergias")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AntecedentesMedicos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionesGeneral")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PacienteNroDoc")
                        .HasColumnType("int");

                    b.Property<string>("PacienteTipoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("NroHC");

                    b.HasIndex("PacienteTipoDoc", "PacienteNroDoc")
                        .IsUnique();

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("Domain.Model.Insumo", b =>
                {
                    b.Property<int>("CodInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodInsumo"));

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int");

                    b.HasKey("CodInsumo");

                    b.ToTable("Insumos");

                    b.HasData(
                        new
                        {
                            CodInsumo = 1,
                            CostoUnitario = 2500m,
                            Nombre = "Kit de Anestesia Local (Mepivacaína)",
                            StockDisponible = 120
                        },
                        new
                        {
                            CodInsumo = 2,
                            CostoUnitario = 6800m,
                            Nombre = "Resina Compuesta Fotocurable",
                            StockDisponible = 45
                        },
                        new
                        {
                            CodInsumo = 3,
                            CostoUnitario = 1500m,
                            Nombre = "Película Radiográfica Periapical",
                            StockDisponible = 200
                        },
                        new
                        {
                            CodInsumo = 4,
                            CostoUnitario = 400m,
                            Nombre = "Guantes de Látex Descartables (Par)",
                            StockDisponible = 500
                        },
                        new
                        {
                            CodInsumo = 5,
                            CostoUnitario = 300m,
                            Nombre = "Babero y Eyector Descartable",
                            StockDisponible = 350
                        },
                        new
                        {
                            CodInsumo = 6,
                            CostoUnitario = 1200m,
                            Nombre = "Pasta para Profilaxis Dental",
                            StockDisponible = 60
                        },
                        new
                        {
                            CodInsumo = 7,
                            CostoUnitario = 4500m,
                            Nombre = "Conos de Gutapercha Endodoncia",
                            StockDisponible = 30
                        });
                });

            modelBuilder.Entity("Domain.Model.Multa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoPago")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("Domain.Model.ObraSocial", b =>
                {
                    b.Property<int>("IdentificadorOS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificadorOS"));

                    b.Property<decimal>("ArancelOS")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EstadoOS")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVA");

                    b.Property<string>("NombreOS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlanCobertura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdentificadorOS");

                    b.ToTable("ObrasSociales");

                    b.HasData(
                        new
                        {
                            IdentificadorOS = 1,
                            ArancelOS = 18000m,
                            EstadoOS = "ACTIVA",
                            NombreOS = "OSDE",
                            PlanCobertura = "Plan 210 / 310"
                        },
                        new
                        {
                            IdentificadorOS = 2,
                            ArancelOS = 22000m,
                            EstadoOS = "ACTIVA",
                            NombreOS = "Swiss Medical",
                            PlanCobertura = "Black / Gold"
                        },
                        new
                        {
                            IdentificadorOS = 3,
                            ArancelOS = 12000m,
                            EstadoOS = "ACTIVA",
                            NombreOS = "IOMA",
                            PlanCobertura = "Afiliados Obligatorios"
                        },
                        new
                        {
                            IdentificadorOS = 4,
                            ArancelOS = 0m,
                            EstadoOS = "ACTIVA",
                            NombreOS = "Particular",
                            PlanCobertura = "Sin cobertura"
                        });
                });

            modelBuilder.Entity("Domain.Model.Pago", b =>
                {
                    b.Property<int>("CodPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPago"));

                    b.Property<decimal?>("AporteObraSocial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AportePaciente")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CodAtencion")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("FechaYHoraPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CodPago");

                    b.HasIndex("CodAtencion")
                        .IsUnique();

                    b.ToTable("Pagos", (string)null);

                    b.HasDiscriminator().HasValue("Pago");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Model.Persona", b =>
                {
                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("NroDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TipoDocumento", "NroDocumento");

                    b.ToTable("Personas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Model.Turno", b =>
                {
                    b.Property<int>("CodTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTurno"));

                    b.Property<int>("CodEspecialidad")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaYHoraCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaYHoraReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaYHoraSolicitudReprogramacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModalidadPagoElegida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OdontologoNroDoc")
                        .HasColumnType("int");

                    b.Property<string>("OdontologoTipoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PacienteNroDoc")
                        .HasColumnType("int");

                    b.Property<string>("PacienteTipoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("TurnoOriginalCod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TurnoOriginalFecha")
                        .HasColumnType("datetime2");

                    b.HasKey("CodTurno");

                    b.HasIndex("CodEspecialidad");

                    b.HasIndex("TurnoOriginalCod");

                    b.HasIndex("OdontologoTipoDoc", "OdontologoNroDoc");

                    b.HasIndex("PacienteTipoDoc", "PacienteNroDoc");

                    b.ToTable("Turnos", (string)null);

                    b.HasDiscriminator().HasValue("Turno");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@turnomolar.com",
                            NombreCompleto = "Administrador Principal",
                            PasswordHash = "admin123",
                            Rol = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "recepcion@turnomolar.com",
                            NombreCompleto = "María López",
                            PasswordHash = "recepcion123",
                            Rol = "Recepcionista",
                            Username = "recepcion"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "mgomez@turnomolar.com",
                            NombreCompleto = "Dr. Martín Gómez",
                            PasswordHash = "doc123",
                            Rol = "Odontologo",
                            Username = "doctor1"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "lrossi@turnomolar.com",
                            NombreCompleto = "Dra. Laura Rossi",
                            PasswordHash = "doc123",
                            Rol = "Odontologo",
                            Username = "doctor2"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Email = "juan.perez@gmail.com",
                            NombreCompleto = "Juan Pérez",
                            PasswordHash = "paciente123",
                            Rol = "Paciente",
                            Username = "paciente1"
                        });
                });

            modelBuilder.Entity("Domain.Model.Valoracion", b =>
                {
                    b.Property<int>("CodValoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodValoracion"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("CodAtencion")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CodValoracion");

                    b.HasIndex("CodAtencion")
                        .IsUnique();

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("Domain.Model.Consulta", b =>
                {
                    b.HasBaseType("Domain.Model.AtencionOdontologica");

                    b.ToTable("AtencionesMedicas", (string)null);

                    b.HasDiscriminator().HasValue("Consulta");
                });

            modelBuilder.Entity("Domain.Model.Factura", b =>
                {
                    b.HasBaseType("Domain.Model.Pago");

                    b.ToTable("Pagos", (string)null);

                    b.HasDiscriminator().HasValue("Factura");
                });

            modelBuilder.Entity("Domain.Model.Odontologo", b =>
                {
                    b.HasBaseType("Domain.Model.Persona");

                    b.Property<int?>("CodDisponibilidad")
                        .HasColumnType("int");

                    b.Property<int?>("CodEspecialidad")
                        .HasColumnType("int");

                    b.Property<string>("EstadoOdontologo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVO");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("CodDisponibilidad");

                    b.HasIndex("CodEspecialidad");

                    b.ToTable("Odontologos", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Paciente", b =>
                {
                    b.HasBaseType("Domain.Model.Persona");

                    b.Property<string>("EstadoPaciente")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HABILITADO");

                    b.Property<int?>("IdentificadorOS")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoAdeudado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("IdentificadorOS");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Domain.Model.TurnoOdontologico", b =>
                {
                    b.HasBaseType("Domain.Model.Turno");

                    b.ToTable("Turnos", (string)null);

                    b.HasDiscriminator().HasValue("TurnoOdontologico");
                });

            modelBuilder.Entity("Domain.Model.AtencionOdontologica", b =>
                {
                    b.HasOne("Domain.Model.Turno", "Turno")
                        .WithOne("Atencion")
                        .HasForeignKey("Domain.Model.AtencionOdontologica", "CodTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Model.HistoriaClinica", "HistoriaClinica")
                        .WithMany()
                        .HasForeignKey("NroHC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Domain.Model.ComprobanteDeTurno", b =>
                {
                    b.HasOne("Domain.Model.Turno", "Turno")
                        .WithOne("Comprobante")
                        .HasForeignKey("Domain.Model.ComprobanteDeTurno", "CodTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Domain.Model.DetalleInsumoUtilizado", b =>
                {
                    b.HasOne("Domain.Model.AtencionOdontologica", "Atencion")
                        .WithMany("DetallesInsumos")
                        .HasForeignKey("CodAtencion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Model.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("CodInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atencion");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("Domain.Model.HistoriaClinica", b =>
                {
                    b.HasOne("Domain.Model.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("Domain.Model.HistoriaClinica", "PacienteTipoDoc", "PacienteNroDoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Model.Pago", b =>
                {
                    b.HasOne("Domain.Model.AtencionOdontologica", "Atencion")
                        .WithOne("Pago")
                        .HasForeignKey("Domain.Model.Pago", "CodAtencion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("Domain.Model.Turno", b =>
                {
                    b.HasOne("Domain.Model.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("CodEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Model.Turno", "TurnoOriginal")
                        .WithMany()
                        .HasForeignKey("TurnoOriginalCod")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Model.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("OdontologoTipoDoc", "OdontologoNroDoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Model.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteTipoDoc", "PacienteNroDoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");

                    b.Navigation("TurnoOriginal");
                });

            modelBuilder.Entity("Domain.Model.Valoracion", b =>
                {
                    b.HasOne("Domain.Model.AtencionOdontologica", "Atencion")
                        .WithOne("Valoracion")
                        .HasForeignKey("Domain.Model.Valoracion", "CodAtencion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("Domain.Model.Odontologo", b =>
                {
                    b.HasOne("Domain.Model.DisponibilidadHoraria", "Disponibilidad")
                        .WithMany()
                        .HasForeignKey("CodDisponibilidad")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Model.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("CodEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Model.Persona", null)
                        .WithOne()
                        .HasForeignKey("Domain.Model.Odontologo", "TipoDocumento", "NroDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disponibilidad");

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("Domain.Model.Paciente", b =>
                {
                    b.HasOne("Domain.Model.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("IdentificadorOS")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Model.Persona", null)
                        .WithOne()
                        .HasForeignKey("Domain.Model.Paciente", "TipoDocumento", "NroDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Domain.Model.AtencionOdontologica", b =>
                {
                    b.Navigation("DetallesInsumos");

                    b.Navigation("Pago");

                    b.Navigation("Valoracion");
                });

            modelBuilder.Entity("Domain.Model.Turno", b =>
                {
                    b.Navigation("Atencion");

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("Domain.Model.Paciente", b =>
                {
                    b.Navigation("HistoriaClinica");
                });
#pragma warning restore 612, 618
        }
    }
}
